apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: yehugh1981/ticketing:payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-service:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE_KEY
                  name: stripe-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: payments